Changes OS for telegram bot.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,80 +1,116 @@
-name: Test the project and update the test-date
+name: Generator
 
 on:
-  schedule:
-    - cron: '0 */12 * * *'
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
+    inputs:
+      account:
+        description: 'Number of Accounts to be generated (default = 0)'
+        required: false
+        default: '0'
+      key:
+        description: 'Number of Keys to be generated (default = 1)'
+        required: false
+        default: '1'
+      mail:
+        description: 'Choose the mail provider to generate license'
+        required: true
+        type: choice
+        options:
+        - 1secmail
+        - guerrillamail
+        - developermail
+        - mailticking
+        - fakemail
+        - inboxes
+        default: developermail
+      key_type:
+        description: 'Modes of operation'
+        required: true
+        type: choice
+        options:
+        - --key
+        - --small-business-key
+        - --vpn-codes
+        default: --key
+      os:
+        description: 'Operating System of runner'
+        required: true
+        type: choice
+        options:
+        - macOS
+        - Linux
+        - Windows
+        default: macOS
 jobs:
-  Test:
-    runs-on: ubuntu-latest
+  GenerateKey:
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest, macos-latest, windows-latest]
+
     steps:
-      - name: 'Checkout Repo'
-        uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Set up Python
+        uses: actions/setup-python@v3
         with:
-          persist-credentials: false
-          fetch-depth: 0
-      - name: 'Generate key and update the test time'
+          python-version: '3.9'
+
+      - name: Install dependencies
         run: |
-          ACCOUNT=0
-          KEY=1
-          SMALL_BUSINESS_KEY=0
-          VPN=1
-          EMAIL_API=developermail
-          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
-          git config --local user.name "github-actions[bot]"
-          git clone --depth 1 https://github.com/rzc0d3r/ESET-KeyGen.git
-          cd ESET-KeyGen
-          # Setup env
-          sudo apt update
-          sudo apt install -y python3-pip python3-venv
-          python3 -m venv venv
-          source venv/bin/activate
+          python -m venv ${{(runner.os == 'Windows' && '.venv') || 'venv'}}
+          source ${{(runner.os == 'Windows' && '.venv\\Scripts\\activate') || 'venv/bin/activate'}}
           pip install -r requirements.txt
-          echo "Test results:" >> $GITHUB_STEP_SUMMARY
-          if [[ ${ACCOUNT} != 0 ]]
-          then
-          for ((attempt=1;attempt<=${ACCOUNT};++attempt))
-          do
-          python3 main.py --chrome --account --email-api ${EMAIL_API} --skip-update-check --no-logo --disable-progress-bar
-          done
-          echo -e "\nAccounts generated:" >> $GITHUB_STEP_SUMMARY
-          cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
+
+      - name: Generating Key
+        run: |
+          # Determine if the workflow was triggered by a manual dispatch or schedule
+          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            KEY=${{ github.event.inputs.key }}
+            MAIL=${{ github.event.inputs.mail }}
+            KEY_TYPE=${{ github.event.inputs.key_type }}
+          else
+            ACCOUNT=0  # Default value for scheduled runs
+            KEY=1     # Default value for scheduled runs
+            MAIL=developermail  # Default mail provider for scheduled runs
+            KEY_TYPE=--vpn-codes  # Default key type for scheduled runs
           fi
-          if [[ ${KEY} != 0 ]]
-          then
-          for ((attempt=1;attempt<=${KEY};++attempt))
-          do
-          python3 main.py --chrome --key --email-api ${EMAIL_API} --skip-update-check --no-logo --disable-progress-bar
-          done
+
+          # Clone the repository (already checked out in the first step)
+          # git clone https://github.com/Shariful797/ESET-KeyGen.git 
+          # cd ESET-KeyGen || exit 1 
+
+          # Function to generate accounts
+          function generate_accounts {
+            seq 1 $1 | xargs -I {} -P $1 python3 main.py --chrome --account --email-api ${MAIL} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar
+          }
+
+          # Function to generate keys
+          function generate_keys {
+            seq 1 $1 | xargs -I {} -P $1 python3 main.py --chrome ${KEY_TYPE} --email-api ${MAIL} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar
+          }
+
+          # Generate based on input parameters
+          if [[ ${ACCOUNT} -ne 0 && ${KEY} -ne 0 ]]; then
+            generate_accounts ${ACCOUNT} &
+            generate_keys ${KEY}
+            wait
+            echo -e "\nAccount:" >> $GITHUB_STEP_SUMMARY
+            cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY || echo "No accounts generated." >> $GITHUB_STEP_SUMMARY
+            echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
+            cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY || echo "No keys generated." >> $GITHUB_STEP_SUMMARY
+          elif [[ ${ACCOUNT} -ne 0 ]]; then
+            generate_accounts ${ACCOUNT}
+            echo -e "\nAccount:" >> $GITHUB_STEP_SUMMARY
+            cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY || echo "No accounts generated." >> $GITHUB_STEP_SUMMARY
+          elif [[ ${KEY} -ne 0 ]]; then
+            generate_keys ${KEY}
+            echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
+            cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY || echo "No keys generated." >> $GITHUB_STEP_SUMMARY
+          else
+            echo "Error! No accounts or keys to generated." >> $GITHUB_STEP_SUMMARY
           fi
-          if [[ ${SMALL_BUSINESS_KEY} != 0 ]]
-          then
-          for ((attempt=1;attempt<=${SMALL_BUSINESS_KEY};++attempt))
-          do
-          python3 main.py --chrome --small-business-key --email-api ${EMAIL_API} --skip-update-check --no-logo --disable-progress-bar
-          done
-          fi
-          if [[ ${VPN} != 0 ]]
-          then
-          for ((attempt=1;attempt<=${VPN};++attempt))
-          do
-          python3 main.py --chrome --vpn-codes --email-api ${EMAIL_API} --skip-update-check --no-logo --disable-progress-bar
-          done
-          fi
-          if [[ ${KEY} != 0 || ${SMALL_BUSINESS_KEY} != 0 || ${VPN} != 0 ]]
-          then
-          echo -e "\nKeys generated:" >> $GITHUB_STEP_SUMMARY
-          cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
-          fi
-          echo 
-          cd ${{ github.workspace }}
-          sed -i '/^ESET-KeyGen - Trial-Key & Account generator/ c\ESET-KeyGen - Trial-Key & Account generator for ESET Products (last test was on '"$(date -u --date='3 hours' +"%d.%m.%Y at %H:%M UTC+3")"')' README.md
-          sudo rm -r ESET-KeyGen
-          git pull
-          git commit -m "Update test time" -a
-      - name: Push changes to the repo
-        uses: ad-m/github-push-action@master
-        with:
-          github_token: ${{ secrets.PAT }}
-          branch: ${{ github.ref }}
+
+          # Deactivate the virtual environment
+          deactivate
